### ISSUE TITLE
unhappy vector

### ISSUE THREAD

**Issue by lucklove** [joyeecheung/my-tech-diary#3]
https://github.com/joyeecheung/my-tech-diary/blob/master/2015/08/2015-08-31.md#L8

> Implementations are required to avoid data races when the contents of the contained object in different elements in the same sequence, excepting vector&lt;bool&gt;, are modified concurrently.
> Without &lt;bool&gt;, vector will be unhappy. ：)

**Comment by joyeecheung** [comment]
https://raw.githubusercontent.com/joyeecheung/my-tech-diary/master/2015/08/2015-08-31.md

Need to escape `<` and `>`, but I don't plan to change my old diaries for correctness because diaries are not source of truth so that sounds ridiculous. I probably will do a big cleanup one day.
